### ISSUE TITLE
首页 · Pytorch 中文文档

### ISSUE THREAD

**Issue by jiangzhonglian** [apachecn/pytorch-doc-zh#367]
https://pytorch.apachecn.org/

**Comment by newhotter** [comment]
0评论终结者

**Comment by fengdshen** [comment]
1评论终结者

**Comment by SylvanLiu** [comment]
2评论终结者

**Comment by newhotter** [comment]
？？？。？



---原始邮件---
发件人: "刘思源"<notifications@github.com&gt;
发送时间: 2020年2月25日(周二) 凌晨5:45
收件人: "apachecn/pytorch-doc-zh"<pytorch-doc-zh@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"newhotter"<10512076@qq.com&gt;;
主题: Re: [apachecn/pytorch-doc-zh] 首页 · Pytorch 中文文档 (#367)



2评论终结者

**Comment by ljflinux** [comment]
## 点开教程 -> 收藏网页 -> 关闭窗口，一气呵成。

**Comment by HarborZeng** [comment]
> @ljflinux
> ## 点开教程 -> 收藏网页 -> 关闭窗口，一气呵成。
> 

你太机智了

**Comment by EricLucife** [comment]
请问从1.0开始没有EPUB等版本。如果要自己做应该怎么弄?

**Comment by liucong12345678** [comment]
怎么下载中文文档啊，怎么没法看啊？

**Comment by YoucanBaby** [comment]
感谢汉化

**Comment by ysh-strive** [comment]
点开教程 -> 收藏网页 -> 关闭窗口，一气呵成。

**Comment by File-saver** [comment]
# 请问 __.whl__ 文件在哪里下？

**Comment by jiangzhonglian** [comment]
> # 请问 **.whl** 文件在哪里下？

我们只提供文档翻译，其他的可以去 http://pytorch.org 下载

**Comment by likeremix715** [comment]
From PyTorch:

Copyright (c) 2016-     Facebook, Inc            (Adam Paszke)
Copyright (c) 2014-     Facebook, Inc            (Soumith Chintala)
Copyright (c) 2011-2014 Idiap Research Institute (Ronan Collobert)
Copyright (c) 2012-2014 Deepmind Technologies    (Koray Kavukcuoglu)
Copyright (c) 2011-2012 NEC Laboratories America (Koray Kavukcuoglu)
Copyright (c) 2011-2013 NYU                      (Clement Farabet)
Copyright (c) 2006-2010 NEC Laboratories America (Ronan Collobert, Leon Bottou, Iain Melvin, Jason Weston)
Copyright (c) 2006      Idiap Research Institute (Samy Bengio)
Copyright (c) 2001-2004 Idiap Research Institute (Ronan Collobert, Samy Bengio, Johnny Mariethoz)

From Caffe2:

Copyright (c) 2016-present, Facebook Inc. All rights reserved.

All contributions by Facebook:
Copyright (c) 2016 Facebook Inc.

All contributions by Google:
Copyright (c) 2015 Google Inc.
All rights reserved.

All contributions by Yangqing Jia:
Copyright (c) 2015 Yangqing Jia
All rights reserved.

All contributions by Kakao Brain:
Copyright 2019-2020 Kakao Brain

All contributions from Caffe:
Copyright(c) 2013, 2014, 2015, the respective contributors
All rights reserved.

All other contributions:
Copyright(c) 2015, 2016 the respective contributors
All rights reserved.

Caffe2 uses a copyright model similar to Caffe: each contributor holds
copyright over their contributions to Caffe2. The project versioning records
all such contribution and copyright details. If a contributor wants to further
mark their specific copyright on a particular contribution, they should
indicate their copyright solely in the commit message of the change when it is
committed.

All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright
   notice, this list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright
   notice, this list of conditions and the following disclaimer in the
   documentation and/or other materials provided with the distribution.

3. Neither the names of Facebook, Deepmind Technologies, NYU, NEC Laboratories America
   and IDIAP Research Institute nor the names of its contributors may be
   used to endorse or promote products derived from this software without
   specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.
